-- Create resources table
create table if not exists public.resources_la2024 (
  id bigint generated by default as identity primary key,
  title text not null,
  description text,
  category text,
  type text,
  size text,
  url text,
  image text,
  downloads bigint default 0,
  premium boolean default false,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS
alter table public.resources_la2024 enable row level security;

-- Create permissive policies because auth is client-side in this project
-- Note: In a production environment with real Supabase Auth, these would be restricted to authenticated users with specific roles.
drop policy if exists "Enable read access for all users" on public.resources_la2024;
create policy "Enable read access for all users"
  on public.resources_la2024 for select
  using (true);

drop policy if exists "Enable insert access for all users" on public.resources_la2024;
create policy "Enable insert access for all users"
  on public.resources_la2024 for insert
  with check (true);

drop policy if exists "Enable update access for all users" on public.resources_la2024;
create policy "Enable update access for all users"
  on public.resources_la2024 for update
  using (true);

drop policy if exists "Enable delete access for all users" on public.resources_la2024;
create policy "Enable delete access for all users"
  on public.resources_la2024 for delete
  using (true);
