-- Create blog_posts table
create table if not exists public.blog_posts_la2024 (
  id bigint generated by default as identity primary key,
  title text not null,
  slug text,
  excerpt text,
  content text,
  category text,
  featured_image text,
  is_featured boolean default false,
  is_published boolean default false,
  read_time text,
  views bigint default 0,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create testimonials table
create table if not exists public.testimonials_la2024 (
  id bigint generated by default as identity primary key,
  name text not null,
  title text,
  company text,
  content text,
  rating integer,
  image_url text,
  is_featured boolean default false,
  is_published boolean default false,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS
alter table public.blog_posts_la2024 enable row level security;
alter table public.testimonials_la2024 enable row level security;

-- Create permissive policies because auth is client-side in this project
create policy "Enable access for all users" on public.blog_posts_la2024 for all using (true) with check (true);
create policy "Enable access for all users" on public.testimonials_la2024 for all using (true) with check (true);
